export const NAV_BAR_COL = "rgba(0, 0, 0, 0)";
export const VIDEO_OVERLAY_COL = "rgba(0, 0, 0, 0.5)";
export const SITE_BG_COL = "#000";
export const SITE_TXT_COL = "#fff";
export const CARD_BORDER_COL = "#8e24aa";
export const UNSELECTED_COL = "#aaa";
export const SHINE_DARK_COL = "#aaa";
export const PURE_WHITE = "rgb(255, 255, 255)"
export const PURE_BLACK = "rgb(0, 0, 0)";